global using System;
global using System.Collections.Generic;
global using System.Linq;
global using RWCustom;
global using UnityEngine;
global using Mono.Cecil.Cil;
global using MonoMod.Cil;
global using Random = UnityEngine.Random;
global using BepInEx;
global using static SlugBase.Features.FeatureTypes;
global using SlugBase.Features;
global using DressMySlugcat;
global using System.Security.Permissions;